In [1]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import StandardScaler

from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.linear_model import Lasso, ElasticNet
from sklearn.neural_network import MLPRegressor

from xgboost import XGBRegressor

In [2]:

# Download all kinases from API

url = "https://kinepik.org/api/0/kinases/all"

response = requests.get(url)

# Convert API response to DataFrame
kinase_df = pd.DataFrame(response.json())

# Keep only UniProt ID and Gene Symbol
kinase_df = pd.DataFrame({
    "UniprotID": kinase_df["UniprotID"],
    "GeneName": kinase_df["GeneInfo"].apply(lambda x: x["MappedGene"])
})

# Display table
kinase_df.head()

  UniprotID GeneName
0    P06239      LCK
1    P12931      SRC
2    P06241      FYN
3    P00519     ABL1
4    P24941     CDK2

In [3]:
print("Total Kinases:", len(kinase_df))

Total Kinases: 504

In [4]:
# get phosphosites for all kinases

def get_phosphosites(kinase_id):

    url = ( "https://kinepik.org/api/0/kinases/specific?"
        f"kinase_ids={kinase_id}&phosphosites=sites"
    )

    response = requests.get(url)
    data = response.json()

    if len(data) ==0:
        return []

    return data[0]["PhosphositesOnKinase"]

In [5]:

# Collect phosphosites for all 504 kinases

all_phosphosites = []

for _, row in kinase_df.iterrows():

    kinase_id = row["UniprotID"]
    gene = row["GeneName"]

    sites = get_phosphosites(kinase_id)

    all_phosphosites.append({
        "UniprotID": kinase_id,
        "GeneName": gene,
        "TotalPhosphosites": len(sites),
        "Phosphosites": sites
    })

phosphosite_df = pd.DataFrame(all_phosphosites)

phosphosite_df.head(10)

,UniprotID,GeneName,TotalPhosphosites,Phosphosites
0,P06239,LCK,6,"[LCK(Y394), LCK(Y505), LCK(Y192), LCK(S42), LC..."
1,P12931,SRC,17,"[SRC(Y216), SRC(Y338), SRC(Y419), SRC(Y530), S..."
2,P06241,FYN,13,"[FYN(Y39), FYN(Y420), FYN(Y28), FYN(Y30), FYN(..."
3,P00519,ABL1,37,"[ABL1(S446), ABL1(S465), ABL1(Y393), ABL1(Y226..."
4,P24941,CDK2,9,"[CDK2(T160), CDK2(Y168), CDK2(S46), CDK2(T165)..."
5,O14757,CHEK1,16,"[CHEK1(S301), CHEK1(S286), CHEK1(S345), CHEK1(..."
6,Q96GD4,AURKB,8,"[AURKB(T232), AURKB(T16), AURKB(S7), AURKB(S33..."
7,P06493,CDK1,12,"[CDK1(S39), CDK1(T161), CDK1(T222), CDK1(Y15),..."
8,O15530,PDPK1,26,"[PDPK1(T513), PDPK1(S241), PDPK1(S393), PDPK1(..."
9,P07949,RET,16,"[RET(Y809), RET(Y1090), RET(Y826), RET(Y1029),..."

In [6]:
# Save phosphosite counts

phosphosite_df.to_csv(
    "phosphosite_counts.csv",
    index=False
)

print("Saved phosphosite_counts.csv")

Saved phosphosite_counts.csv

In [7]:
# get fc values for one phosphosite

def get_fc(phosphosite):

    url = ( "https://kinepik.org/api/0/perturbation/fc?"
        f"type=target_phosphosite&id={phosphosite}"
        "&cell_line=NTERA2&confidence=1"
    )

    response = requests.get(url)

    return response.json()

In [8]:
# Download FC data for all phosphosites

fc_rows = []

for _, row in phosphosite_df.iterrows():

    kinase_id = row["UniprotID"]
    gene = row["GeneName"]

    for site in row["Phosphosites"]:

        try:
            fc_data = get_fc(site)

            for record in fc_data:

                info = record[site]

                fc_rows.append({
                    "UniprotID": kinase_id,
                    "GeneName": gene,
                    "Phosphosite": site,
                    "Perturbation": info["Perturbation"],
                    "CellLine": info["CellLine"],
                    "FC": float(info["FC"])   # <-- FIXED
                })

        except:
            continue

fc_df = pd.DataFrame(fc_rows)

In [9]:
fc_df.to_csv(
    "fc_NTERA2.csv",
    index=False
)

print("Saved fc_NTERA2.csv")

Saved fc_NTERA2.csv

In [10]:
print("Number of FC rows:", len(fc_rows))

Number of FC rows: 46421

In [10]:
print(fc_df.shape)

fc_df.head()

fc_df.columns

fc_df.info()

(46482, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46482 entries, 0 to 46481
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   UniprotID     46482 non-null  object
 1   GeneName      46482 non-null  object
 2   Phosphosite   46482 non-null  object
 3   Perturbation  46482 non-null  object
 4   CellLine      46482 non-null  object
 5   FC            46482 non-null  float64
dtypes: float64(1), object(5)
memory usage: 2.1+ MB

In [11]:
ksea_rows = []

In [12]:
# Download KSEA for every kinase

for _, row in kinase_df.iterrows():

    kinase_id = row["UniprotID"]
    gene = row["GeneName"]

    # only perturbations that exist for this kinase
    kinase_fc = fc_df[fc_df["UniprotID"] == kinase_id]

    perturbations = kinase_fc["Perturbation"].unique()

    print(f"{gene}: {len(perturbations)} perturbations")

    for pert in perturbations:

        try:

            url = (
                f"https://kinepik.org/api/0/perturbation/KSEA?"
                f"kinase_ids={kinase_id}"
                f"&perturbations={pert}"
                f"&cell_line=NTERA2"
            )

            response = requests.get(url)
            data = response.json()

            z_score = data[0][kinase_id][pert]["z_score"]

            ksea_rows.append({
                "UniprotID": kinase_id,
                "GeneName": gene,
                "Perturbation": pert,
                "CellLine": "NTERA2",
                "KSEA_z_score": z_score
            })

        except:
            continue

LCK: 0 perturbations
SRC: 61 perturbations
FYN: 0 perturbations
ABL1: 61 perturbations
CDK2: 61 perturbations
CHEK1: 61 perturbations
AURKB: 0 perturbations
CDK1: 61 perturbations
PDPK1: 61 perturbations
RET: 61 perturbations
MAP3K7: 61 perturbations
PRKCQ: 61 perturbations
IKBKB: 61 perturbations
JAK2: 61 perturbations
CHEK2: 0 perturbations
ATM: 61 perturbations
TTK: 61 perturbations
PLK1: 61 perturbations
CAMK2A: 0 perturbations
MAPK3: 61 perturbations
MAPK1: 61 perturbations
EGFR: 61 perturbations
PRKCA: 61 perturbations
CSNK2A1: 0 perturbations
GSK3A: 61 perturbations
GSK3B: 61 perturbations
INSR: 0 perturbations
UHMK1: 0 perturbations
AKT2: 0 perturbations
PAK1: 61 perturbations
MAPK14: 0 perturbations
CDK7: 61 perturbations
KSR1: 61 perturbations
PAK3: 0 perturbations
PRKDC: 61 perturbations
ERBB2: 61 perturbations
NTRK1: 0 perturbations
MAPKAPK5: 61 perturbations
VRK1: 0 perturbations
DYRK2: 61 perturbations
HIPK2: 61 perturbations
AURKA: 0 perturbations
DAPK1: 0 perturbations
MAPKAPK2: 0 perturbations
RPS6KB2: 61 perturbations
PRKD1: 61 perturbations
MAPK8: 0 perturbations
MAPK9: 0 perturbations
PRKCD: 61 perturbations
CSK: 0 perturbations
PDGFRB: 0 perturbations
WEE1: 61 perturbations
MKNK1: 0 perturbations
MKNK2: 61 perturbations
CSF1R: 0 perturbations
GRK2: 61 perturbations
GRK5: 0 perturbations
IGF1R: 0 perturbations
CSNK1A1: 0 perturbations
LYN: 0 perturbations
PDK1: 0 perturbations
PDK2: 0 perturbations
PDK3: 0 perturbations
PDK4: 0 perturbations
MET: 61 perturbations
PRKCE: 0 perturbations
HCK: 61 perturbations
ROCK1: 61 perturbations
PRKG1: 0 perturbations
FGR: 0 perturbations
RPS6KB1: 61 perturbations
FGFR1: 61 perturbations
PRKCB: 0 perturbations
PTK2: 61 perturbations
CSNK1D: 61 perturbations
CDK5: 61 perturbations
MAPK7: 0 perturbations
DAPK3: 61 perturbations
DYRK3: 0 perturbations
RPS6KA3: 61 perturbations
RPS6KA2: 0 perturbations
CAMK4: 61 perturbations
ATR: 61 perturbations
MAPK13: 0 perturbations
TYK2: 61 perturbations
RPS6KA1: 61 perturbations
FLT1: 0 perturbations
CDK3: 61 perturbations
SYK: 61 perturbations
MAP2K4: 0 perturbations
CHUK: 61 perturbations
FGFR4: 0 perturbations
YES1: 0 perturbations
MTOR: 61 perturbations
LIMK1: 61 perturbations
LIMK2: 0 perturbations
TESK1: 0 perturbations
TESK2: 61 perturbations
PAK2: 61 perturbations
CDK9: 61 perturbations
CSNK1E: 61 perturbations
MAP2K1: 0 perturbations
CDK4: 0 perturbations
FLT4: 0 perturbations
ZAP70: 0 perturbations
JAK1: 0 perturbations
PIM1: 0 perturbations
BRSK1: 0 perturbations
PLK3: 0 perturbations
GRK4: 0 perturbations
ILK: 61 perturbations
PRKCZ: 0 perturbations
SIK1: 0 perturbations
TRPM7: 61 perturbations
KDR: 0 perturbations
TGFBR2: 61 perturbations
MAP3K5: 0 perturbations
DYRK1B: 61 perturbations
ALK: 0 perturbations
IRAK1: 61 perturbations
BTK: 61 perturbations
MAP2K7: 61 perturbations
PTK6: 0 perturbations
DYRK1A: 61 perturbations
AAK1: 61 perturbations
STK10: 61 perturbations
RAF1: 61 perturbations
MAP3K8: 61 perturbations
RPS6KA5: 0 perturbations
IKBKE: 0 perturbations
TBK1: 0 perturbations
CDK6: 0 perturbations
TXK: 0 perturbations
MAP4K1: 0 perturbations
HIPK3: 61 perturbations
MAPK12: 0 perturbations
PTK2B: 61 perturbations
BMPR1B: 0 perturbations
TGFBR1: 0 perturbations
STK11: 61 perturbations
MAP2K6: 61 perturbations
FES: 61 perturbations
PRKACA: 61 perturbations
EPHA3: 0 perturbations
EPHA4: 0 perturbations
EPHA8: 0 perturbations
FGFR3: 61 perturbations
KIT: 61 perturbations
MST1R: 0 perturbations
ITK: 0 perturbations
TEK: 0 perturbations
EPHB3: 0 perturbations
CLK1: 61 perturbations
IRAK4: 0 perturbations
JAK3: 0 perturbations
MERTK: 0 perturbations
MAPK6: 0 perturbations
TLK1: 61 perturbations
MAP3K14: 0 perturbations
EIF2AK2: 0 perturbations
NEK2: 0 perturbations
PRKCH: 0 perturbations
NEK6: 61 perturbations
CDK19: 0 perturbations
GRK6: 61 perturbations
EIF2AK1: 61 perturbations
EIF2AK3: 61 perturbations
CAMK1: 61 perturbations
GRK1: 0 perturbations
EPHB2: 0 perturbations
BLK: 0 perturbations
PDGFRA: 0 perturbations
PRP4K: 61 perturbations
LRRK2: 0 perturbations
MAPK4: 0 perturbations
MAPK11: 0 perturbations
MAP3K11: 61 perturbations
GRK3: 0 perturbations
TEC: 0 perturbations
CDC42BPA: 61 perturbations
MAP2K3: 0 perturbations
PRKG2: 0 perturbations
MAPK10: 0 perturbations
TNK2: 61 perturbations
STK4: 61 perturbations
ROCK2: 0 perturbations
NEK9: 61 perturbations
PASK: 61 perturbations
PAK5: 0 perturbations
NLK: 0 perturbations
WNK1: 61 perturbations
NUAK1: 0 perturbations
ABL2: 61 perturbations
PRKCG: 0 perturbations
PRKCI: 61 perturbations
PRKD2: 61 perturbations
DAPK2: 0 perturbations
CILK1: 0 perturbations
STK38: 0 perturbations
STK38L: 0 perturbations
STK24: 0 perturbations
BMX: 0 perturbations
CAMKK1: 61 perturbations
EPHA2: 0 perturbations
MAP3K1: 61 perturbations
MAP4K2: 61 perturbations
FLT3: 0 perturbations
AKT1: 61 perturbations
SRPK2: 61 perturbations
PAK4: 61 perturbations
TLK2: 61 perturbations
SGK1: 0 perturbations
CDK8: 0 perturbations
PLK2: 0 perturbations
PLK4: 0 perturbations
VRK2: 0 perturbations
MAPKAPK3: 0 perturbations
SIK2: 61 perturbations
PRKAA2: 61 perturbations
MARK2: 61 perturbations
SGK3: 61 perturbations
CAMK2G: 61 perturbations
NUAK2: 0 perturbations
STK3: 61 perturbations
CDK14: 61 perturbations
CDC7: 0 perturbations
MYLK: 61 perturbations
MYLK3: 0 perturbations
NEK11: 0 perturbations
MELK: 61 perturbations
WNK4: 0 perturbations
HIPK4: 61 perturbations
PRKX: 0 perturbations
DMPK: 0 perturbations
CLK2: 61 perturbations
CAMK2D: 61 perturbations
CAMK2B: 61 perturbations
AURKC: 0 perturbations
TTBK1: 61 perturbations
MARK1: 61 perturbations
TAF1: 0 perturbations
RPS6KA4: 61 perturbations
LATS2: 61 perturbations
LATS1: 61 perturbations
CAMKK2: 61 perturbations
PKMYT1: 61 perturbations
DDR1: 0 perturbations
CDK20: 0 perturbations
CAMK1D: 0 perturbations
MAP3K20: 61 perturbations
STK16: 0 perturbations
TAOK1: 61 perturbations
MAP2K2: 61 perturbations
MINK1: 61 perturbations
ACVR1B: 0 perturbations
FER: 0 perturbations
FRK: 0 perturbations
PRKAA1: 61 perturbations
CDK12: 61 perturbations
PHKG2: 0 perturbations
PHKG1: 0 perturbations
CSNK1G1: 0 perturbations
TRRAP: 61 perturbations
MOS: 0 perturbations
TAOK2: 61 perturbations
MASTL: 61 perturbations
TSSK1B: 0 perturbations
CSNK2A2: 0 perturbations
PKN1: 61 perturbations
BUB1: 61 perturbations
AKT3: 0 perturbations
EIF2AK4: 61 perturbations
MAP2K5: 0 perturbations
CIT: 61 perturbations
BRAF: 61 perturbations
TAOK3: 61 perturbations
MAP3K12: 0 perturbations
RIPK2: 61 perturbations
STK39: 61 perturbations
PINK1: 0 perturbations
PRKACB: 0 perturbations
EPHB1: 0 perturbations
EEF2K: 61 perturbations
CSNK1A1L: 0 perturbations
PRKACG: 0 perturbations
PRKD3: 61 perturbations
NEK7: 0 perturbations
OXSR1: 61 perturbations
NTRK2: 0 perturbations
MAP3K6: 0 perturbations
RIPK1: 61 perturbations
CDKL5: 61 perturbations
RIPK3: 61 perturbations
SIK3: 61 perturbations
BRD4: 61 perturbations
ULK3: 0 perturbations
CDK11A: 61 perturbations
NEK8: 0 perturbations
MAP4K3: 0 perturbations
PAK6: 0 perturbations
PKN3: 0 perturbations
PBK: 61 perturbations
TTN: 61 perturbations
MAPK15: 0 perturbations
CLK4: 61 perturbations
BRSK2: 61 perturbations
TNIK: 61 perturbations
MAP3K21: 61 perturbations
MAP3K4: 61 perturbations
CSNK1G2: 0 perturbations
SMG1: 61 perturbations
PIM3: 0 perturbations
SRPK1: 61 perturbations
CDK10: 61 perturbations
PNCK: 0 perturbations
MAP3K3: 61 perturbations
WNK2: 61 perturbations
HIPK1: 61 perturbations
SGK2: 0 perturbations
CDC42BPB: 61 perturbations
CDK18: 61 perturbations
ULK2: 0 perturbations
MARK3: 61 perturbations
AXL: 0 perturbations
MYLK2: 0 perturbations
WNK3: 61 perturbations
MAK: 0 perturbations
STYK1: 0 perturbations
PIM2: 0 perturbations
MYO3A: 0 perturbations
STK19: 0 perturbations
MAP3K10: 0 perturbations
STK25: 61 perturbations
BCKDK: 61 perturbations
RIOK3: 0 perturbations
ULK1: 61 perturbations
TSSK3: 0 perturbations
STK17A: 61 perturbations
LMTK2: 0 perturbations
CAMK1G: 0 perturbations
MAP4K5: 61 perturbations
ADCK5: 0 perturbations
BMPR1A: 0 perturbations
ACVR2B: 0 perturbations
ARAF: 61 perturbations
FGFR2: 0 perturbations
TP53RK: 0 perturbations
TTBK2: 0 perturbations
NEK3: 61 perturbations
BCR: 61 perturbations
TRPM6: 0 perturbations
NEK1: 61 perturbations
MAP3K9: 61 perturbations
MATK: 61 perturbations
PDIK1L: 0 perturbations
CDK16: 61 perturbations
NRK: 61 perturbations
ACVR1: 0 perturbations
PRKCH: 0 perturbations
CDK17: 61 perturbations
MARK4: 61 perturbations
EPHA1: 61 perturbations
TIE1: 0 perturbations
DYRK4: 0 perturbations
HUNK: 0 perturbations
ERBB4: 0 perturbations
RPS6KA6: 61 perturbations
LTK: 0 perturbations
BMP2K: 61 perturbations
SLK: 61 perturbations
GAK: 0 perturbations
STK33: 61 perturbations
LRRK1: 0 perturbations
GRK7: 0 perturbations
PKN2: 61 perturbations
MAP3K13: 0 perturbations
ACVRL1: 0 perturbations
ALPK1: 0 perturbations
CASK: 0 perturbations
NEK5: 0 perturbations
CDKL2: 0 perturbations
TYRO3: 0 perturbations
MAST3: 61 perturbations
MAP3K2: 61 perturbations
CLK3: 61 perturbations
MAP4K4: 61 perturbations
ERN1: 0 perturbations
SRMS: 0 perturbations
CDK15: 0 perturbations
VRK3: 61 perturbations
CDK13: 61 perturbations
CSNK1G3: 61 perturbations
SCYL2: 0 perturbations
TNNI3K: 0 perturbations
DCLK1: 61 perturbations
NRBP2: 0 perturbations
DDR2: 61 perturbations
SCYL3: 61 perturbations
FASTK: 0 perturbations
MAST2: 61 perturbations
NEK4: 61 perturbations
CDKL3: 0 perturbations
PRKY: 0 perturbations
NPR2: 0 perturbations
SCYL1: 0 perturbations
TRIB3: 0 perturbations
NTRK3: 0 perturbations
BMPR2: 61 perturbations
MAST1: 61 perturbations
TRIB2: 0 perturbations
NRBP1: 0 perturbations
STK40: 0 perturbations
STK36: 0 perturbations
PXK: 0 perturbations
HASPIN: 61 perturbations
RIOK1: 61 perturbations
KSR2: 0 perturbations
PIK3R4: 0 perturbations
SNRK: 61 perturbations
AGER: 0 perturbations
MOK: 61 perturbations
MAP3K19: 0 perturbations
IRAK3: 0 perturbations
STK17B: 0 perturbations
TSSK4: 0 perturbations
CDC42BPG: 61 perturbations
EPHB4: 61 perturbations
ROS1: 0 perturbations
ERBB3: 61 perturbations
GUCY2C: 0 perturbations
PTK7: 0 perturbations
MAP3K15: 0 perturbations
TRIM28: 61 perturbations
LMTK3: 0 perturbations
PEAK1: 61 perturbations
RIPK4: 0 perturbations
STRADA: 0 perturbations
ROR1: 61 perturbations
BUB1B: 61 perturbations
HSPB8: 61 perturbations
ROR2: 61 perturbations
MLKL: 0 perturbations
KALRN: 0 perturbations
RIOK2: 61 perturbations
TRIO: 61 perturbations
TRIM24: 61 perturbations
TNK1: 61 perturbations
NPR1: 0 perturbations
TEX14: 0 perturbations
TRIM33: 61 perturbations
CAMKV: 61 perturbations
BRD2: 61 perturbations
BRD3: 61 perturbations
AATK: 0 perturbations
RYK: 61 perturbations
IRAK2: 0 perturbations
AMHR2: 0 perturbations
EPHA5: 0 perturbations
EPHA6: 0 perturbations
EPHA7: 0 perturbations
EPHB6: 0 perturbations
ACVR2A: 0 perturbations
OBSCN: 61 perturbations
BRDT: 0 perturbations
ACVR1C: 0 perturbations
GUCY2D: 0 perturbations
MUSK: 0 perturbations
TAF1L: 0 perturbations
STRADB: 0 perturbations
COQ8A: 0 perturbations
TSSK2: 0 perturbations
STK35: 0 perturbations
TRIB1: 0 perturbations
PSKH1: 0 perturbations
RNASEL: 0 perturbations
GUCY2F: 0 perturbations
RPS6KC1: 61 perturbations
SRPK3: 0 perturbations
CDKL1: 0 perturbations
ADCK1: 0 perturbations
INSRR: 61 perturbations
ULK4: 0 perturbations
COQ8B: 0 perturbations
ANKK1: 0 perturbations
DCLK2: 0 perturbations
DCLK3: 0 perturbations
MYO3B: 0 perturbations
DSTYK: 0 perturbations
SBK1: 0 perturbations
STK32A: 0 perturbations
STK32B: 0 perturbations
STK32C: 61 perturbations
NEK10: 0 perturbations
EPHA10: 0 perturbations
ERN2: 0 perturbations
ADCK2: 0 perturbations
ALPK2: 0 perturbations
ALPK3: 61 perturbations
PSKH2: 0 perturbations
TSSK6: 0 perturbations
STK31: 0 perturbations
RPS6KL1: 0 perturbations
CDKL4: 0 perturbations
STKLD1: 0 perturbations

In [13]:
ksea_df = pd.DataFrame(ksea_rows)

In [14]:
print(ksea_df.shape)
ksea_df.head()

(13841, 5)

  UniprotID GeneName Perturbation CellLine  KSEA_z_score
0    P12931      SRC      AZD6482   NTERA2      1.812098
1    P12931      SRC       CAL101   NTERA2      1.146269
2    P12931      SRC      GDC0941   NTERA2      1.631653
3    P12931      SRC        HS173   NTERA2      1.744843
4    P12931      SRC       PIK294   NTERA2     -0.228499

In [15]:
ksea_df.to_csv("ksea_NTERA2.csv", index=False)